using System;

class Except
{
    public static void Throw()
    {
        throw new Exception("Error: Success");
    }
}